### ISSUE TITLE
Panic with rustc 1.27.0-nightly (4b9b70c39 2018-04-09)

### ISSUE THREAD

**Issue by ordovicia** [regexident/cargo-modules#14]
Sorry if this is not caused by cargo-modules.

Running `cargo modules` panics.

```
$ cargo new modules-test
     Created binary (application) `modules-test` project
$ cd modules-test/
$ cargo +nightly modules
thread 'main' panicked at 'cannot access a scoped thread local variable without calling `set` first', /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.1/src/lib.rs:186:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Meta:

```
$ rustc +nightly --version
rustc 1.27.0-nightly (4b9b70c39 2018-04-09)

$ cargo +nightly modules --version
cargo-modules 0.3.6
```

Backtrace:

```
$ RUST_BACKTRACE=1 cargo +nightly modules
thread 'main' panicked at 'cannot access a scoped thread local variable without calling `set` first', /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.1/src/lib.rs:186:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic
   6: <scoped_tls::ScopedKey<T>>::with
   7: syntax_pos::symbol::Ident::from_str
   8: syntax::parse::lexer::StringReader::next_token_inner
   9: syntax::parse::lexer::StringReader::advance_token
  10: syntax::parse::lexer::StringReader::new
  11: syntax::parse::filemap_to_stream
  12: syntax::parse::filemap_to_parser
  13: syntax::parse::parse_crate_from_file
  14: cargo_modules::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:305
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:284
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  19: main
  20: __libc_start_main
  21: _start
```

**Comment by regexident** [comment]
@ordovicia could you try again with 0.4.0 and report whether it's fixed for you?

**Comment by ordovicia** [comment]
@regexident cargo-modules v0.4.0 with rustc 1.27.0-nightly (ac5c0848d 2018-05-14) no longer panics.
Thank you!

**Comment by regexident** [comment]
> Thank you!

@hmvp did all the work for that! :wink:
