### ISSUE TITLE
internal compiler error: Error constructed but not emitted

### ISSUE THREAD

**Issue by evnu** [regexident/cargo-modules#25]
When running `cargo modules tree` (`cargo-modules 0.4.3`) on a crate which cannot compile, an internal compiler error is emitted. For example, create a crate and introduce an obvious error:

```rust
$ cargo init reproduce --lib
$ cd reproduce
$ cat > src/lib.rs <<EOF
# src/lib.rs
mod does_not_exist;
EOF
$ RUST_BACKTRACE=1 rustup run nightly cargo modules tree
error: internal compiler error: Error constructed but not emitted

thread 'main' panicked at 'explicit panic', /home/evnu/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_errors-263.0.0/diagnostic_builder.rs:308:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::begin_panic
   6: <rustc_errors::diagnostic_builder::DiagnosticBuilder<'a> as core::ops::drop::Drop>::drop
   7: <scoped_tls::ScopedKey<T>>::set
   8: syntax::with_globals
   9: cargo_modules::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```

Can this be handled by `cargo-modules`?

**Comment by regexident** [comment]
I suppose one could probably wrap the call on [`syntax::with_globals`](https://github.com/regexident/cargo-modules/blob/master/src/main.rs#L105-L156) in [`panic::catch_unwind`](http://doc.rust-lang.org/1.29.1/std/panic/fn.catch_unwind.html) and print something like `Error: Crate failed to compile.`? 🤔

**Comment by evnu** [comment]
A simple error  message would be sufficient I think.

**Comment by regexident** [comment]
This should now be fixed with https://github.com/regexident/cargo-modules/pull/66 having been merged. 🎉 😃
<sub>(The release still needs a it more work. If you're feeling lucky you can install from source and give it a try, though.)</sub>
